# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cf056ed9fca4a354f997757ff7a66f67a71e35b01583ff0cb114e994541642259e2794f3dd6e0a51afefa6d3820e9fc9b25664c96d250551e21d9eff33ad90c

test:
  secret_key_base: 09adff659d3a44f5db1a1d77449a4a797346dad139503ec814364880bad49e02848b65cacafbaed738bfc9dc01a5e6f6e61304f5790646e7b480c2289934c4dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
